### ISSUE TITLE
Proton GE By Glorious EggRoll

### ISSUE THREAD

**Issue by JoneKone** [ninelore/armaonlinux#17]
Hi.

I use Proton GE usually on my Windows games. Can I use this script to make that work too? I did try to read the code but.. Well All I saw that there is no reference to this directory .steam/debian-installation/compatibilitytools.d 

I quest my real question is, why does this script care about the version that Arma is run under.

**Comment by ninelore** [comment]
Hey, 

You are able to use Proton-GE (against recommendation) by filling out `PROTON_CUSTOM_VERSION=""` with the folder name without path in the settings.

what folders do you have in `~/.steam/`?

**Comment by JoneKone** [comment]
.steam/debian-installation/compatibilitytools.d/GE-Proton7-16

Why do you say against recommendation? Are you saying this cause anti-cheat? Or is it somebody else saying it?

**Comment by ninelore** [comment]
> Why do you say against recommendation? Are you saying this cause anti-cheat? Or is it somebody else saying it?

Atm there's no technical reason not to run official plus it rules out one possible problem source.

> what folders do you have in ~/.steam/?

`ls -lah $HOME/.steam`
