### ISSUE TITLE
Add option to start Arma 3 launcher

### ISSUE THREAD

**Issue by DanielGaaA** [ninelore/armaonlinux#18]
Hello,

when teamspeak is already running steam will not let you launch Arma3 because its already "running". It would be great to have option launch arma3 with this script same way as we do with teamspeak.

**Comment by ninelore** [comment]
In its current its not really viable to add that to the script. I got something in the works but thats early developement

**Comment by ninelore** [comment]
Closing because the mentioned current state wont change anytime soon
