### ISSUE TITLE
Add line on TS3 plugins to documentation

### ISSUE THREAD

**Issue by bapking** [ninelore/armaonlinux#21]
Thanks for this fantastic guide, everything works perfectly!

The one thing I would suggest is adding a line about installing TFAR/ACRE's plugins as it took me a little bit of digging to find the correct folder.

It could read "Once Teamspeak is ready to go you can install plugins by adding the relevant dll to /home/<NAME>/.steam/root/steamapps/compatdata/107410/pfx/drive_c/users/steamuser/Application Data/TS3Client/plugins"

**Comment by ninelore** [comment]
moved to right repo

**Comment by BagelSeasoning234** [comment]
@bapking Thanks for the tip! It looks like the ACRE2 plugin was installed automatically into teamspeak when I subscribed to the TFAR mod on the Steam workshop, but the TFAR one didn't show up in the addons section until I found the dll files following [this guide ](https://forums.ahoyworld.net/topic/12153-how-to-install-tfar-and-the-teamspeak-addon/) and moved them to the plugin folder you mentioned in your post.
