### ISSUE TITLE
script is slow, and does not work with the latest version of proton

### ISSUE THREAD

**Issue by Pockets-byte** [ninelore/armaonlinux#24]
sic, the script dumps me down from solid 40+ fps to 20, doesn't function with the newest version of proton, experimental or 8.0, and is getting quite irritating to have to deal with in general, updates please?

**Comment by ninelore** [comment]
Specs?  
Logs?  
Mods?  

I have conflicting report that it is working fine

**Comment by Pockets-byte** [comment]
OS: Fedora Linux 37 (MATE-Compiz) x86_64 
Host: 20WE ThinkBook 14s Yoga ITL 
Kernel: 6.2.8-200.fc37.x86_64 
Shell: bash 5.2.15 
Resolution: 1920x1080 
Terminal: mate-terminal 
CPU: 11th Gen Intel i7-1165G7 (8) @ 4.700GHz 
GPU: Intel TigerLake-LP GT2 [Iris Xe Graphics] 
Memory: 11294MiB / 15777MiB 


mods lots. but probably a moot point because arma mods shouldn't affect teamspeak, just a whole bunch of the standard stuff, errors varied, but often stated that the wrong version of wine was installed. I'll need a bit to actually get the errors from the script

**Comment by Pockets-byte** [comment]
13076
wine client error:0: version mismatch 759/743.
Your wine binary was not upgraded correctly,
or you have an older one somewhere in your PATH.
Or maybe the wrong wineserver is still running?

**Comment by Pockets-byte** [comment]
Update
it turns out the issue isn't with the script, but with the config file. edited the script directly and it worked
