### ISSUE TITLE
Does not work when stuff is installed on different drives

### ISSUE THREAD

**Issue by royalmustard** [ninelore/armaonlinux#6]
I have steam on one drive, proton on another and arma on a third one. Your script assumes all are installed in the default steam location

**Comment by ninelore** [comment]
1v15 has support for proton and arma all in different librarys. [1](https://github.com/ninelore/armaonlinux/blob/master/Arma3TS_1v15-0.sh#L12-L14) [2](https://github.com/ninelore/armaonlinux/blob/master/Arma3TS_1v15-0.sh#L20-L23)

Either you didnt read the script or you have a outdated version.
