### ISSUE TITLE
[Bug] Arma3TS_1v16-0.sh can't find Proton directory

### ISSUE THREAD

**Issue by Thadah** [ninelore/armaonlinux#8]
Hi, since the version change to support experimental versions the script is unable to find the Proton 6.3 folder because the whitespace character isn't escaped in https://github.com/ninelore/armaonlinux/blob/master/Arma3TS_1v16-0.sh#L18.

```sh: line 1: /home/<user>/.local/share/Steam/steamapps/common/Proton: No such file or directory```

Escaping the whitespace like ```PROTON_OFFICIAL_VERSION="Proton\ 6.3"``` solves the issue for me.

**Comment by fjp321** [comment]
same issue, escape in that string fixed issue

**Comment by ninelore** [comment]
fixed with #9
